# Basic travis script
#language: objective-c  #1
#osx_image: xcode7.3 #2
#xcode_workspace: CIiOSExampleApp.xcworkspace #3
#xcode_scheme: CIiOSExampleApp #4
#xcode_sdk: iphoneos #5

---
after_failure:
- ./scripts/sign-and-upload.sh
after_script:
- ./scripts/remove-key.sh
after_success:
- ./scripts/sign-and-upload.sh
before_install:
- "chmod a+x scripts/config.sh"
- "chmod +x scripts/add-key.sh"
- "chmod +x scripts/remove-key.sh"
- "chmod +x scripts/update-bundle.sh"
- "chmod +x scripts/sign-and-upload.sh"
before_script:
- ". ./scripts/config.sh"
- ./scripts/add-key.sh
- ./scripts/update-bundle.sh

language: objective-c
osx_image: xcode7.3
notifications:
email:
recipients:
#- v2_mobile_tykoonapp_ios@v2solutions.com
on_failure: always
on_success: always
script:
- APP_BUILD_ENV=DEV
- "if [ \"$TRAVIS_BRANCH\" = \"QA\" ]; then APP_BUILD_ENV=QA; echo \"QA Scheme Selected.\"; elif [ \"$TRAVIS_BRANCH\" = \"master\" ]; then APP_BUILD_ENV=DEV; echo \"UAT Scheme Selected.\"; fi"
- "xctool -workspace \"$APP_WORKSPACE_PATH\" -scheme \"$APP_SCHEME.$APP_BUILD_ENV\" -sdk iphoneos -configuration \"$APP_BUILD_ENV\" OBJROOT=\"$PWD/build\" SYMROOT=\"$PWD/build\" ONLY_ACTIVE_ARCH=NO"
- "xctool test -workspace \"$APP_WORKSPACE_PATH\" -scheme \"$APP_SCHEME.$APP_BUILD_ENV\" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO"
